Repository paketo-buildpacks/node-engine, pull requests merged in 2024-06, with the labels that each got.

#924 Remove deprecated node versions 16 and 19
  buildpack.toml
  integration/openssl_test.go
Labels: semver:major

#939 Add support for Node.js `v22`
  buildpack.toml
Labels: semver:minor

#941 Add info about version support
  README.md
Labels: semver:patch
